### PR TITLE
chore: Unpin dependencies

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/17480

### CODE REVIEW

**Review by jlipps — COMMENTED** [review]
why get rid of renovate? it is superior to dependabot in many ways

**Comment by mykola-mokhnach** [comment]
Dependabot does not create PRs for minor and patch updates while renovate does. I was not able to find a configuration option to disable that behavior

**Comment by jlipps** [comment]
renovate can turn on auto merging for minor/patch updates when tests pass. is that not what we would want?

**Comment by mykola-mokhnach** [comment]
I don't need automerge, just want to not see these PRs being created at all as they are already covered by version ranges

**Comment by jlipps** [comment]
hmm, i'm trying to remember the name of the renovate team member that helped us earlier, i bet he has some idea about this. i couldn't find it in the old PRs, do you have any recollection?

**Comment by boneskull** [comment]
I think we should merge #102 instead.  Renovate is doing what it should, but it's not smart enough to automatically understand that an upgrade to `@appium/eslint-config-appium` v7 requires eslint* updates to be in the same PR (we have to explicitly tell it so).

**Comment by mykola-mokhnach** [comment]
Closed as obsolete

**Pull request closed without merging**
